In [103]:
import numpy as np
arr1=np.random.randint(0,10,(10,2))
arr2=np.random.randint(0,2,(10,1))
norm=np.random.normal(0,1,(3,3)) #평균 0 분산 1
arr3=np.arange(4,dtype=float)
arr4=np.zeros((3,3))
arr5=np.ones((3,3))
a=np.arange(0,5)
b=np.arange(5,10)
c=np.concatenate([a,b])
d=np.concatenate([arr1,arr2],axis=1)
left,right=np.split(d,[2],axis=1)
copy=up.copy()

In [106]:
print(arr1.shape)
print(arr2.shape)
arr1+arr2
#broadcast

(10, 2)
(10, 1)


array([[ 9,  4],
       [ 1, 10],
       [ 7,  3],
       [ 4, 10],
       [ 1,  4],
       [ 1,  6],
       [ 1,  9],
       [ 1,  3],
       [ 6,  0],
       [ 0,  6]])

Masking

In [54]:
array=np.arange(16).reshape(4,4)
print(array<5)
array[array<5]=100
print(array)

[[ True  True  True  True]
 [ True False False False]
 [False False False False]
 [False False False False]]
[[100 100 100 100]
 [100   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]


In [72]:
t=np.arange(16).reshape(4,4)
print(t)
print('t max : ',t.max())
print('t min : ',t.min())
print('t sum : ',t.sum())
print('t mean : ',t.mean())
print('sumn of axis=1 : ',t.sum(axis=1))
print('mean of axis=0 : ',t.mean(axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
t max :  15
t min :  0
t sum :  120
t mean :  7.5
sumn of axis=1 :  [ 6 22 38 54]
mean of axis=0 :  [6. 7. 8. 9.]


save numpy

In [71]:
n=np.arange(10)
np.save('save.npy',n)
load=np.load('save.npy')
p=np.arange(10,20)
np.savez('save.npz',arr1=n,arr2=p)
n1=np.load('save.npz')['arr1']
p1=np.load('save.npz')['arr2']
print(n1)
print(p1)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


sort

In [99]:
s=np.random.randint(0,10,10)
print(s)
s.sort() #ascending-True
print(s)
print(s[::-1]) #ascending=False

[7 6 5 8 2 2 0 1 2 3]
[0 1 2 2 2 3 5 6 7 8]
[8 7 6 5 3 2 2 2 1 0]


In [128]:
m=np.array([[1,4,5,3,2],[5,3,4,1,2]])
print(np.sort(m,axis=0)) #열 기준 정렬

[[1 3 4 1 2]
 [5 4 5 3 2]]


In [120]:
ar=np.linspace(0,10,5)
print(ar)

[ 0.   2.5  5.   7.5 10. ]


In [126]:
dupl=np.random.randint(0,4,5)
print(dupl)
print(np.unique(dupl))
print(set(dupl))

[3 3 1 2 1]
[1 2 3]
{1, 2, 3}
